#!/usr/bin/env bash
# Copyright © 2026 mindicator & silicon bags quartet.
# SPDX-License-Identifier: AGPL-3.0-or-later
# This file is part of Mycelium, licensed under the GNU Affero General Public License v3.0 or
# later. See the LICENSE file in the repository root.
#
# aggregate_outbound_go_equiv.sh — conformance: the Go share-link PARSER (spec.OutboundFromLink,
# `myceliumctl link-outbound`) is BYTE-IDENTICAL to the shell `myc_agg_link_outbound` across the transport
# matrix (RP-0008 P3-c, the strangler equivalence gate for the aggregate's link parser — the inverse of
# the P3-a share-link renderer). Links are generated by the proven Go share-link (P3-a) — including a
# reserved char in every encodable field, so the encode->splice->parse->decode round-trip is exercised —
# then parsed by BOTH producers and diffed. A ShadowTLS link must yield the shell's fail-closed `null` on
# both sides. Until green the shell stays authoritative (no cutover).
# Author: mindicator & silicon bags quartet.
#
# SKIP-IF-NO-GO: the offline jq-only host cannot run the Go side (mirrors the other *_go_equiv gates); the
# Go-node / CI lane runs the diff. The Go-side unit test TestOutboundFromLink pins it where Go is absent.
#
# Exit: 0 = byte-identical (or skipped without Go); 1 = a parsed outbound diverged; 2 = usage/env error.

set -uo pipefail
HERE="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${MYC_REPO_ROOT:-$(cd -P "$HERE/../.." && pwd)}"
LIB="$REPO_ROOT/control/lib"
command -v jq >/dev/null 2>&1 || { printf 'FAIL: jq is required.\n' >&2; exit 2; }

printf '== aggregate link-outbound Go↔shell byte-equivalence (RP-0008 P3-c) ==\n'
printf 'repo: %s\n' "$REPO_ROOT"

GO=""
if command -v go >/dev/null 2>&1; then GO="$(command -v go)"; else
	for c in /usr/local/go/bin/go /usr/lib/go-1.26/bin/go /usr/lib/go/bin/go; do [ -x "$c" ] && { GO="$c"; break; }; done
fi
if [ -z "$GO" ]; then
	printf 'SKIP: no Go toolchain — the Go-node/CI lane runs the link-parser byte-equivalence (TestOutboundFromLink mirrors it).\n'
	exit 0
fi
WORK="$(mktemp -d "${TMPDIR:-/tmp}/myc.aoge.XXXXXX")" || { printf 'FAIL: mktemp failed.\n' >&2; exit 2; }
trap 'rm -rf "$WORK"' EXIT
SPINE="$WORK/spine"
if ! ( cd "$REPO_ROOT" && GOCACHE="$WORK/gocache" GOFLAGS=-mod=mod GOPROXY=off GOSUMDB=off CGO_ENABLED=0 "$GO" build -o "$SPINE" ./cmd/myceliumctl ) >/dev/null 2>&1; then
	printf 'FAIL: could not build the Go spine.\n' >&2; exit 2
fi

# Source the shell parser (myc_agg_link_outbound) + its deps.
export MYC_LIB="$LIB" MYC_ROOT="$REPO_ROOT/control"
# shellcheck disable=SC1090
. "$LIB/common.sh"           || { printf 'FAIL: cannot source common.sh\n' >&2; exit 2; }
. "$LIB/jqlib.sh"            || { printf 'FAIL: cannot source jqlib.sh\n' >&2; exit 2; }
. "$LIB/render_aggregate.sh" || { printf 'FAIL: cannot source render_aggregate.sh\n' >&2; exit 2; }
command -v myc_agg_link_outbound >/dev/null 2>&1 || { printf 'FAIL: myc_agg_link_outbound not defined after sourcing\n' >&2; exit 2; }

# Fixture LinkParams: reserved chars in every encodable field (the round-trip stress).
json="$(jq -n '{
	server:"node.example.invalid", port:"8443", uuid:"uid/1+2 a", donor_sni:"www.microsoft.com",
	pub:"aB-cd_EF12", short_id:"0e6e7757", tls_sni:"tls.example.invalid",
	ss_password:"ss/pw+1=x", hy2_password:"hy2:pw@2", trojan_password:"tr&pw#3", tuic_password:"tuic pw?4",
	grpc_service_name:"grpc.health.v1.Health", xhttp_path:"/x?a=1", xhttp_path_tls:"/xt#y", ws_path:"/ws&z" }')"

PROTOS="$(jq -r '[.protos[] | select(.scheme != "") | .proto] | join(" ")' "$REPO_ROOT/control/vocab.json")"
[ -n "$PROTOS" ] || { printf 'FAIL: no link-bearing protos in vocab.json\n' >&2; exit 2; }

fail=0
for proto in $PROTOS; do
	link="$(printf '%s' "$json" | "$SPINE" share-link --proto "$proto" - 2>/dev/null)"
	[ -n "$link" ] || { printf '  FAIL  %s: share-link produced no link\n' "$proto"; fail=1; continue; }
	sh_ob="$(myc_agg_link_outbound "node-$proto" "$link")"
	go_ob="$("$SPINE" link-outbound --tag "node-$proto" "$link" 2>/dev/null)"
	go_rc=$?

	# WHAT EQUIVALENCE MEANS FOR A LINK THAT MUST NOT BECOME AN OUTBOUND AT ALL.
	#
	# Two links in the matrix are not representable as one sing-box outbound, for different reasons:
	# ShadowTLS is a PAIR (outer shadowsocks + shadowtls detour), and xhttp is an Xray-only carrier that
	# sing-box has no transport type for — a profile containing one is rejected WHOLE, not merely unable
	# to dial (measured 2026-08-17).
	#
	# The two producers say so differently, and that difference is DELIBERATE. The shell function is a
	# library call inside render_aggregate.sh, whose caller dies on a `null`; it must therefore return one.
	# The Go `link-outbound` is a VERB whose output goes straight to a human or a script, so it REFUSES
	# with the cause instead of printing a JSON null that jq would splice into an outbound list — which is
	# how an unloadable profile got built and reported as success.
	#
	# So for these two the assertion is the MEANING, not the bytes: neither side yields a usable outbound.
	# Comparing the bytes here would pin the very behaviour that produced the defect.
	if [ "$(printf '%s' "$sh_ob" | tr -d '[:space:]')" = "null" ] || [ -z "$sh_ob" ]; then
		if [ "$go_rc" -ne 0 ] && [ -z "$go_ob" ]; then
			printf '  ok    %s — neither producer yields an outbound (shell: null, go: refusal with a cause)\n' "$proto"
		else
			printf '  FAIL  %s: the shell refuses this link but Go emitted an outbound (%s). A link sing-box cannot use must not reach a client profile from either producer.\n' "$proto" "$(printf '%s' "$go_ob" | cut -c1-60)"
			fail=1
		fi
		continue
	fi
	if [ "$go_rc" -ne 0 ]; then
		# The shell rendered something and Go refused. Legitimate only where Go knows the target engine
		# cannot load it — spec.OutboundSkipReason is the single owner of that knowledge.
		# CAPTURE, THEN GREP. `"$SPINE" ... | grep -q` under `set -o pipefail` returns the verb's own
		# non-zero — it refused, which is the whole point — so the pipeline reports failure even when grep
		# matched. That is the same benign-non-zero trap fixed three times elsewhere in this tree today,
		# and it bit this row on its first run.
		go_err="$("$SPINE" link-outbound --tag t "$link" 2>&1 || true)"
		if grep -qE 'sing-box cannot load|cannot be expressed|ShadowTLS is a pair' <<<"$go_err" ; then
			printf '  ok    %s — the shell renders it, Go refuses with a stated engine reason (recorded open defect: the renderers still emit it)\n' "$proto"
		else
			printf '  FAIL  %s: Go refused without naming an engine reason:\n    %s\n' "$proto" "$(printf '%s' "$go_err" | head -1)"
			fail=1
		fi
		continue
	fi
	if [ "$sh_ob" = "$go_ob" ]; then
		printf '  ok    %s\n' "$proto"
	else
		printf '  FAIL  %s diverged:\n    shell: %s\n    go:    %s\n' "$proto" "$sh_ob" "$go_ob"
		fail=1
	fi
done

printf '\n-- Result --\n'
if [ "$fail" -eq 0 ]; then
	printf 'PASS: spec.OutboundFromLink is byte-identical to myc_agg_link_outbound across the transport matrix.\n'
	exit 0
fi
printf 'FAIL: a parsed outbound diverged between shell and Go — do NOT cut over (RP-0008 P3 equivalence).\n' >&2
exit 1
