#!/usr/bin/env bash
# Copyright © 2026 mindicator & silicon bags quartet.
# SPDX-License-Identifier: AGPL-3.0-or-later
# This file is part of Mycelium, licensed under the GNU Affero General Public License v3.0 or
# later. See the LICENSE file in the repository root.
#
# params_validation_single_owner.sh — conformance: a structured operator-settable params knob is judged
# by exactly ONE implementation, and every params key a renderer reads is reachable by an operator.
# Author: mindicator & silicon bags quartet.
#
# WHY THIS GATE EXISTS (ADR-0038, RP-0017; development.md §2.2 item 8)
#   A hysteria2 hop range is a promise the CLIENT CONFIG makes and the FIREWALL keeps: the renderers emit
#   `server_ports`, and a nat/PREROUTING REDIRECT delivers that range onto the one port the inbound holds.
#   When those consumers judged the value separately they diverged, and the resulting state is invisible
#   FROM THE NODE — clients hop across ports nothing serves while verify_post_apply reports healthy,
#   because it checks the service, the bind and a LOOPBACK handshake, and loopback never traverses
#   PREROUTING.
#
#   THE FIRST REMEDIATION WAS ITSELF THE DEFECT THIS GATE NOW PREVENTS. It added a Go predicate, hand-copied
#   the rule into both shell halves, and gated the three against one value table. That is a policed
#   duplication: §2.2 item 8 forbids two locations holding one truth outright, the gate had to be kept
#   current against three sites plus its own `sed`-extracted fourth copy, and it could not see a FIFTH
#   consumer added later. A gate that watches N implementations agree is evidence the rule was not applied.
#
#   So this gate asserts the opposite property: there is no second implementation to disagree with.
#
# WHAT IT CHECKS
#   1. SINGLE OWNER. The policy — the bounds, the shape, the ordering — appears only in internal/spec.
#      No shell file re-derives it: no port-bound literal, no second range parse. The one shell
#      comparator (common.sh) is permitted precisely because it compares against EMITTED numbers.
#   2. EMITTED, NOT RESTATED. control/vocab.json carries .params_validation, and the numbers there are the
#      ones the Go owner holds (proven by vocab_single_source's byte-diff; asserted here as presence+shape).
#   3. FAIL-CLOSED WITHOUT BOUNDS. An artifact carrying no bounds must yield NO range — the unconfigured
#      state — never a permissive default. This is the state a partially-updated node is in.
#   4. THE COMPARATOR IS CORRECT, over a value table driven against the shipped function.
#   5. REACHABILITY AS A CLASS (ADR-0038 consequence 3). Every params key a renderer consumes must be
#      reachable by exactly one of three routes: generated by write_params, in the Go-owned operator
#      allowlist, or stamped by a named posture step. A knob in none of them is not "off by default" —
#      it is unsettable, which is how port hopping shipped and could not be enabled by anyone.
#   6. THE OPERATOR OVERLAY ROUND TRIP, driven against the SHIPPED merge_operator_overrides — never a
#      reproduction of its jq program, because a reproduction stays green while the real reduce loses the key.
#
# OFFLINE. No root, no network. Exit: 0 = single-sourced and reachable; 1 = not; 2 = usage/env error.

set -uo pipefail

HERE="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${MYC_REPO_ROOT:-$(cd -P "$HERE/../.." 2>/dev/null && pwd)}"
[ -n "$REPO_ROOT" ] || { printf 'params_validation_single_owner: cannot resolve repo root\n' >&2; exit 2; }
COMMON="$REPO_ROOT/control/lib/common.sh"
PARAMS_LIB="$REPO_ROOT/control/lib/nb_render_params.sh"
RENDER="$REPO_ROOT/control/lib/render_singbox.sh"
HARDEN="$REPO_ROOT/control/lib/nb_harden.sh"
VOCAB="$REPO_ROOT/control/vocab.json"
SPEC="$REPO_ROOT/internal/spec/transport.go"
for f in "$COMMON" "$PARAMS_LIB" "$RENDER" "$HARDEN" "$VOCAB" "$SPEC"; do
	[ -f "$f" ] || { printf 'params_validation_single_owner: missing %s\n' "$f" >&2; exit 2; }
done
command -v jq >/dev/null 2>&1 || { printf 'params_validation_single_owner: jq required\n' >&2; exit 2; }

fail=0
ok()    { printf '  ok    %s\n' "$1"; }
badln() { printf '  FAIL  %s\n' "$1"; fail=1; }

WORK="$(mktemp -d "${TMPDIR:-/tmp}/myc.pvso.XXXXXX")" || exit 2
trap 'rm -rf "$WORK"' EXIT

printf '== params-knob validation: one owner, and every knob reachable ==\n'

# ---------------------------------------------------------------------------------------------------
# 1. SINGLE OWNER — no shell file may re-derive the policy.
# ---------------------------------------------------------------------------------------------------
printf '\n-- the policy lives in exactly one place --\n'

# The port bounds as NUMBERS. Their presence in shell is the signature of a re-derivation: a consumer
# that compares against emitted values never needs to name them. Comments are stripped so prose that
# EXPLAINS the bounds does not read as an implementation of them.
strip_comments() { sed 's/[[:space:]]#.*$//; s/^[[:space:]]*#.*$//' "$1"; }

# SCOPED TO THE HOP RANGE, deliberately. An earlier draft flagged any shell file naming 1024 or 65535
# and reported three libraries that merely bound a SINGLE port to the protocol range — ordinary
# validation, not a second copy of this policy. A gate that cannot tell a duplicated rule from an
# unrelated constant teaches people to ignore it. The invariant is therefore about files that TOUCH the
# hop range: they may delegate, and they may not decide.
# WHAT a consumer may DO with the value — not what its file happens to contain elsewhere. Two earlier
# drafts scoped this per-FILE and both produced false alarms, flagging libraries that bound an unrelated
# single port to 1..65535. render_singbox.sh both consumes the hop range and validates a two-hop port, so
# no file-level rule can separate them. The invariant is per LINE: every line touching the hop range must
# be a read, a pass-through, a clear, or a delegation. Anything else is a decision, and deciding is the
# owner's job.
# SCOPED TO THE FUNCTION, which is the only granularity that works. Per-FILE was too coarse: two drafts
# flagged libraries that merely bound an unrelated single port to 1..65535, and render_singbox.sh both
# consumes the hop range and validates a two-hop port, so no file-level rule can separate them. Per-LINE
# was too narrow, and the mutation proved it: a re-implementation operates on a local variable and never
# names the key again, so restoring the deleted parser into _hy2_hop_range left the gate fully green.
#
# A FUNCTION that reads the hop range must delegate and must not decide: it may call the comparator, and
# it may not name a bound or split the value into fields.
offenders=""
checked=0
for f in "$REPO_ROOT"/control/lib/*.sh; do
	base="$(basename "$f")"
	[ "$base" = common.sh ] && continue          # holds the one permitted comparator, checked separately
	# Function names in this tree are `name() {` at column 0; bodies end at a lone `}`.
	for fn in $(grep -oE '^[a-z_][a-z0-9_]*\(\)' "$f" | tr -d '()'); do
		body="$(sed -n "/^${fn}() {/,/^}$/p" "$f" | sed 's/[[:space:]]#.*$//; s/^[[:space:]]*#.*$//')"
		# CONSUMERS only: a function that READS the value from params must delegate. A function that
		# merely emits the key in the defaults object (write_params) or names it in a message to the
		# operator (converge_node_tail) consumes nothing and has nothing to delegate — requiring it to
		# call the comparator reported both as violations while neither ever judges a value.
		printf '%s' "$body" | grep -qE "myc_params_get[^\\n]*\\.hysteria2_hop_ports|jq -r '\\.hysteria2_hop_ports" || continue
		checked=$((checked + 1))
		printf '%s' "$body" | grep -qE '\b(1024|65535)\b' \
			&& offenders="$offenders${offenders:+; }$base:$fn names a port bound"
		printf '%s' "$body" | grep -qE '%%:\*|##\*:' \
			&& offenders="$offenders${offenders:+; }$base:$fn splits the range itself"
		printf '%s' "$body" | grep -q 'myc_hop_range_ok' \
			|| offenders="$offenders${offenders:+; }$base:$fn reads the range and never delegates to the comparator"
	done
done
[ "$checked" -ge 2 ] \
	|| badln "found only $checked function(s) handling the hop range; both the client renderer and the firewall reconcile must appear, or this section is inspecting the wrong thing"
[ -z "$offenders" ] \
	&& ok "every function that handles the hop range delegates and decides nothing ($checked checked)" \
	|| badln "$offenders. Two expressions of one rule is the divergence that let a client be handed a range the firewall would refuse, invisibly: verify_post_apply checks the service, the bind and a LOOPBACK handshake, and loopback never traverses PREROUTING (development.md §2.2 item 8)."

# common.sh may hold the comparator but must READ the bounds, never state them.
if strip_comments "$COMMON" | grep -qE '\b(1024|65535)\b'; then
	badln "common.sh names a port bound. It is allowed to hold the single shell COMPARATOR, not the policy — the numbers must come from control/vocab.json .params_validation, which internal/spec emits."
else
	ok "the shell comparator reads its bounds rather than stating them"
fi
strip_comments "$COMMON" | grep -q 'params_validation.hysteria2_hop_ports' \
	&& ok "and it reads them from the emitted artifact" \
	|| badln "common.sh does not read .params_validation from the vocab — then whatever it compares against is not the owner's value"

# Exactly one shell function may DECIDE a hop range.
deciders="$(grep -rlE '^myc_hop_range_ok\(\)' "$REPO_ROOT"/control/lib/*.sh 2>/dev/null | wc -l | tr -d ' ')"
[ "${deciders:-0}" = "1" ] \
	&& ok "exactly one shell function decides a hop range" \
	|| badln "found $deciders definitions of the shell hop-range comparator; there must be exactly one, in common.sh — the only file BOTH shell entrypoints (myceliumctl and node-bootstrap) source"

# The Go owner must actually be the owner.
grep -q 'func ValidHysteria2HopRange' "$SPEC" \
	&& ok "internal/spec holds the predicate" \
	|| badln "internal/spec no longer exports the hop-range predicate — the owner named by ADR-0038 is gone"
grep -q 'hysteria2HopPortBounds = PortRangeBounds' "$SPEC" \
	&& ok "and the bounds are named constants with a recorded basis (development.md §1.1)" \
	|| badln "the bounds are not named constants in internal/spec — a numeric network parameter must be named and tied to a decision"

# ---------------------------------------------------------------------------------------------------
# 2. EMITTED, NOT RESTATED.
# ---------------------------------------------------------------------------------------------------
printf '\n-- the artifact carries what the shell needs --\n'
vmin="$(jq -r '.params_validation.hysteria2_hop_ports.min // empty' "$VOCAB")"
vmax="$(jq -r '.params_validation.hysteria2_hop_ports.max // empty' "$VOCAB")"
viv="$(jq -r '.params_validation.hysteria2_hop_interval_default // empty' "$VOCAB")"
if [ -n "$vmin" ] && [ -n "$vmax" ] && [ -n "$viv" ]; then
	ok "control/vocab.json emits the bounds ($vmin..$vmax) and the interval default ($viv)"
else
	badln "control/vocab.json carries no .params_validation. Every shell consumer then fails closed and NO node can enable port hopping — regenerate it: go run ./cmd/myceliumctl vocab > control/vocab.json"
fi

# ---------------------------------------------------------------------------------------------------
# 3-4. THE COMPARATOR, driven. Including the artifact-without-bounds case.
# ---------------------------------------------------------------------------------------------------
printf '\n-- the shipped comparator, over a value table --\n'
# NOTE ON `1024:65535` (Audit-0010 F-001). It is pinned ACCEPT here because this comparator judges the
# range's SYNTAX AND ENDPOINTS and nothing else — that is its whole contract. It is not a statement that
# the value is safe to configure: a REDIRECT over the whole port space swallows every other served UDP
# family on the node. That refusal belongs to reconcile_hy2_hop_nat, which is the only place that knows
# which ports THIS node serves, and hy2_hop_redirect_kept.sh drives it.
(
	set -u
	# shellcheck source=/dev/null
	. "$COMMON" || exit 2
	MYC_VOCAB="$VOCAB"

	fail=0
	while IFS='|' read -r value want; do
		[ -n "${value}${want}" ] || continue
		if myc_hop_range_ok "$value"; then got=accept; else got=refuse; fi
		label="$(printf '%s' "${value:-<пусто>}" | sed 's/ /␣/g')"
		[ "$got" = "$want" ] \
			&& printf '  ok    %s -> %s\n' "'$label'" "$want" \
			|| { printf '  FAIL  %s: the comparator says %s, expected %s. A value it accepts is emitted to every client AND written into a firewall rule; a value it refuses must reach neither.\n' "'$label'" "$got" "$want"; fail=1; }
	done <<'ROWS'
20000:21000|accept
1024:65535|accept
2000:2001|accept
|refuse
abc|refuse
20000|refuse
:20000|refuse
20000:|refuse
0:100|refuse
1023:2000|refuse
20000:70000|refuse
5000:4000|refuse
5000:5000|refuse
2000:3000:4000|refuse
20000:21000:5|refuse
 20000:21000|refuse
20000:21000 |refuse
-1:500|refuse
1e4:2e4|refuse
001024:065535|refuse
0001024:0002000|refuse
020000:21000|refuse
0000000000000000000000000000002000:3000|refuse
ROWS

	# THE HOP INTERVAL, judged by the same owner (Audit-0010 F-005). It was operator-settable and
	# validated by nobody, so a mistyped duration reached the client config and the server render and
	# sing-box refused the whole document — a converge failing every tick with a message about JSON.
	while IFS='|' read -r value want; do
		[ -n "${value}${want}" ] || continue
		if myc_hop_interval_ok "$value"; then got=accept; else got=refuse; fi
		[ "$got" = "$want" ] \
			&& printf '  ok    interval %s -> %s\n' "'${value:-<пусто>}'" "$want" \
			|| { printf '  FAIL  interval %s: comparator says %s, expected %s\n' "'$value'" "$got" "$want"; fail=1; }
	done <<'IROWS'
30s|accept
3s|accept
2m|accept
1h|accept
500ms|accept
|refuse
30|refuse
s|refuse
0s|refuse
-5s|refuse
30sec|refuse
1h2m3s|refuse
30S|refuse
IROWS

	# THE PARTIALLY-UPDATED NODE. An artifact with no bounds must refuse everything — no range, hence no
	# rule, hence the unconfigured state. A permissive default here would hand clients a range with
	# nothing behind it, which is the precise failure this contract exists to remove.
	jq 'del(.params_validation)' "$VOCAB" >"$WORK/vocab.nobounds.json" 2>/dev/null || exit 1
	MYC_VOCAB="$WORK/vocab.nobounds.json"
	if myc_hop_range_ok "20000:21000"; then
		printf '  FAIL  an artifact carrying NO bounds still accepted a range. That is the state a partially-updated node is in, and a permissive default there advertises a range no firewall rule backs.\n'; fail=1
	else
		printf '  ok    an artifact with no bounds refuses every range (fail-closed)\n'
	fi
	# And an artifact that is missing entirely.
	MYC_VOCAB="$WORK/does-not-exist.json"
	myc_hop_range_ok "20000:21000" \
		&& { printf '  FAIL  a MISSING artifact accepted a range\n'; fail=1; } \
		|| printf '  ok    a missing artifact refuses every range (fail-closed)\n'
	exit "$fail"
) || fail=1

# ---------------------------------------------------------------------------------------------------
# 5. REACHABILITY AS A CLASS.
# ---------------------------------------------------------------------------------------------------
printf '\n-- every knob a renderer reads must be settable by someone --\n'
# Anchored INSIDE write_params: the first `jq -n` in that file belongs to seed_operator_overrides, and an
# unanchored range reads that helper instead of the defaults object.
GENERATED="$(sed -n '/^write_params()/,/^}$/p' "$PARAMS_LIB" \
	| sed -n "/jq -n/,/>\"\$tmp\"/p" | grep -oE '[a-z0-9_]+:' | tr -d ':' | sort -u)"
ALLOWED="$(jq -r '.operator_toggle_keys[]?' "$VOCAB" | sort -u)"
# The third legitimate route: a dedicated posture step that stamps a key (apply_reachability_posture
# writes .node_bind from the node profile). Counting only the first two reported node_bind as unsettable.
STAMPED="$(grep -rhoE "jq [^|]*'\.[a-z0-9_]+ *=" "$REPO_ROOT"/control/lib/*.sh 2>/dev/null \
	| sed -E "s/.*'\.([a-z0-9_]+) *=.*/\1/" | sort -u)"
READ_KEYS="$( { grep -oE "paramStr\(params, \"[a-z0-9_]+\"" "$REPO_ROOT/internal/spec/subscription.go" | sed -E 's/.*"([a-z0-9_]+)"/\1/'
                grep -oE "myc_params_get \"\\\$params\" '\.[a-z0-9_]+'" "$RENDER" | sed -E "s/.*'\.([a-z0-9_]+)'/\1/"
              } | sort -u )"
for n in GENERATED ALLOWED STAMPED READ_KEYS; do
	eval "v=\$$n"
	[ -n "$v" ] || badln "could not derive $n — this whole section would pass vacuously, which is how the unsettable knob survived its own gate"
done

unreachable=""
for k in $READ_KEYS; do
	printf '%s\n' "$GENERATED" | grep -qx "$k" && continue
	printf '%s\n' "$ALLOWED"   | grep -qx "$k" && continue
	printf '%s\n' "$STAMPED"   | grep -qx "$k" && continue
	unreachable="$unreachable $k"
done
[ -z "$unreachable" ] \
	&& ok "every params key the renderers consume is generated, operator-settable, or posture-stamped" \
	|| badln "a renderer reads these keys and NOTHING can set them:$unreachable. write_params regenerates params.json from a fixed object and merge_operator_overrides honours only the Go-owned allowlist, so a hand-edited value is erased by the next converge — every timer tick on an armed node. Such a knob is not 'off by default', it is unsettable, and the feature it belongs to cannot be turned on by anyone."

# ---------------------------------------------------------------------------------------------------
# 6. THE OVERLAY ROUND TRIP, against the SHIPPED merge.
# ---------------------------------------------------------------------------------------------------
printf '\n-- an operator-set value survives the regeneration --\n'
(
	set -u
	STATE_DIR="$WORK"
	log()  { :; }
	warn() { :; }
	die()  { printf 'lib: %s\n' "$*" >&2; exit 1; }
	have() { command -v "$1" >/dev/null 2>&1; }
	# shellcheck source=/dev/null
	. "$PARAMS_LIB" 2>/dev/null || exit 1
	OPERATOR_OVERRIDES="$WORK/ovr.json"
	OPERATOR_TOGGLE_KEYS="$(jq -ec '.operator_toggle_keys' "$VOCAB")"
	printf '{"hysteria2_enabled":true,"hysteria2_hop_ports":"20000:21000"}\n' >"$OPERATOR_OVERRIDES"
	jq -n '{hysteria2_enabled:false, hysteria2_port:8444, hysteria2_hop_ports:"", hysteria2_hop_interval:"30s"}' >"$WORK/defaults.json"
	# DRIVEN, not reproduced. A copy of the jq program stays green while the real reduce loses the key —
	# so the defect the contract exists to prevent would be fully reintroducible under a passing gate.
	merge_operator_overrides "$WORK/defaults.json" || exit 1
	[ "$(jq -r '.hysteria2_hop_ports' "$WORK/defaults.json")" = "20000:21000" ] || exit 1
	[ "$(jq -r '.hysteria2_enabled' "$WORK/defaults.json")" = "true" ] || exit 1
) \
	&& ok "an operator-set range and enable survive merge_operator_overrides" \
	|| badln "the operator value did not survive the shipped merge — it is dropped on the next converge while every issued config still advertises it"

printf '\n-- Result --\n'
if [ "$fail" -ne 0 ]; then
	printf 'FAIL: params-knob validation is not single-sourced, or a knob is unreachable.\n' >&2
	exit 1
fi
printf 'PASS: one owner decides, the artifact carries it, the shell compares, and every knob is reachable.\n'
exit 0
