# Copyright © 2026 mindicator & silicon bags quartet.
# SPDX-License-Identifier: AGPL-3.0-or-later
# This file is part of Mycelium, licensed under the GNU Affero General Public License v3.0 or
# later. See the LICENSE file in the repository root.
#
# common.sh — shared helpers for myceliumctl (logging, dependency checks, jq wrappers).
# Author: mindicator & silicon bags quartet.
#
# This file is meant to be sourced, never executed directly. It defines functions only;
# it must not mutate global shell state beyond defining functions and read-only constants.

# ---------------------------------------------------------------------------
# Logging — everything goes to stderr so stdout stays machine-parseable.
# ---------------------------------------------------------------------------

myc_log() {
	printf 'myceliumctl: %s\n' "$*" >&2
}

myc_warn() {
	printf 'myceliumctl: warning: %s\n' "$*" >&2
}

# myc_die MESSAGE [EXIT_CODE]
# Print an error and exit. Default exit code is 1.
myc_die() {
	local code
	code="${2:-1}"
	printf 'myceliumctl: error: %s\n' "$1" >&2
	exit "$code"
}

# ---------------------------------------------------------------------------
# Dependency checks. We require only audited, off-the-shelf tools. We never
# hand-roll cryptography: REALITY keypairs and UUIDs come from xray, shortIds
# come from openssl. See docs/adr/0002-no-custom-cryptography.md.
# ---------------------------------------------------------------------------

# myc_have CMD -> 0 if CMD is on PATH, 1 otherwise.
myc_have() {
	command -v "$1" >/dev/null 2>&1
}

# myc_require CMD [HINT]
# Abort with a clear message if CMD is not on PATH.
myc_require() {
	local cmd hint
	cmd="$1"
	hint="${2:-}"
	if ! myc_have "$cmd"; then
		if [ -n "$hint" ]; then
			myc_die "required command not found in PATH: '$cmd' ($hint)"
		fi
		myc_die "required command not found in PATH: '$cmd'"
	fi
}

# myc_require_jq — jq is the rendering engine for Phase 0; it is mandatory.
myc_require_jq() {
	myc_require jq "install jq; it is the JSON rendering engine for Phase 0 tooling"
}

# myc_require_xray — REALITY keys and UUIDs MUST come from xray. We never
# generate them ourselves: no custom cryptography (ADR-0002).
myc_require_xray() {
	myc_require xray "install xray-core (>= v26.2.4) and put 'xray' on PATH; \
REALITY keypairs and UUIDs are generated by xray, never by hand"
}

# myc_require_openssl — shortIds are random hex from openssl rand.
myc_require_openssl() {
	myc_require openssl "install openssl; shortIds are generated with 'openssl rand -hex'"
}

# ---------------------------------------------------------------------------
# Crypto-material generators. THESE ARE WRAPPERS ONLY. Not one byte of key
# material is produced by this codebase — it all comes from audited tools.
# ---------------------------------------------------------------------------

# myc_xray_uuid — emit a single UUID from `xray uuid`.
myc_xray_uuid() {
	myc_require_xray
	local out
	out="$(xray uuid 2>/dev/null | tr -d '[:space:]')"
	if [ -z "$out" ]; then
		myc_die "'xray uuid' produced no output"
	fi
	printf '%s\n' "$out"
}

# myc_shortid [BYTES] — emit a REALITY shortId as lowercase hex.
# Default 8 bytes -> 16 hex chars (a common REALITY shortId length).
myc_shortid() {
	myc_require_openssl
	local bytes out
	bytes="${1:-8}"
	out="$(openssl rand -hex "$bytes" 2>/dev/null | tr -d '[:space:]')"
	if [ -z "$out" ]; then
		myc_die "'openssl rand -hex $bytes' produced no output"
	fi
	printf '%s\n' "$out"
}

# ---------------------------------------------------------------------------
# Timestamps. RFC 3339 / ISO 8601 UTC, second precision, portable across the
# BSD date on macOS and GNU date on Linux.
# ---------------------------------------------------------------------------

myc_now_utc() {
	date -u +%Y-%m-%dT%H:%M:%SZ
}

# ---------------------------------------------------------------------------
# Filesystem helpers.
# ---------------------------------------------------------------------------

# myc_mkdir_p DIR — create DIR (and parents) or die.
myc_mkdir_p() {
	mkdir -p -- "$1" || myc_die "could not create directory: $1"
}

# myc_dirname_of FILE — directory holding FILE.
myc_dirname_of() {
	dirname -- "$1"
}

# myc_atomic_write FILE < CONTENT
# Read stdin into FILE atomically (write to temp in the same dir, then mv).
myc_atomic_write() {
	local dest dir tmp
	dest="$1"
	dir="$(myc_dirname_of "$dest")"
	myc_mkdir_p "$dir"
	tmp="$(mktemp "${dir}/.myc.XXXXXX")" || myc_die "could not create temp file in $dir"
	cat >"$tmp" || { rm -f "$tmp"; myc_die "could not write temp file for $dest"; }
	mv -f "$tmp" "$dest" || { rm -f "$tmp"; myc_die "could not move temp file into place: $dest"; }
}
