# Copyright © 2026 mindicator & silicon bags quartet.
# SPDX-License-Identifier: AGPL-3.0-or-later
# This file is part of Mycelium, licensed under the GNU Affero General Public License v3.0 or
# later. See the LICENSE file in the repository root.
#
# common.sh — the helpers BOTH shell entrypoints source: logging, dependency checks, jq wrappers, and
# the single comparator for emitted params-knob validation (ADR-0038).
#
# The last responsibility is here for a stated reason rather than by drift: myceliumctl and
# node-bootstrap each judge a hysteria2 hop range, node-bootstrap does not source lib/vocab.sh, and this
# is the only file both reach. Keeping the comparator anywhere else would mean two of them, which is the
# defect ADR-0038 exists to remove. It holds no policy — it compares against numbers internal/spec emits.
# Author: mindicator & silicon bags quartet.
#
# This file is meant to be sourced, never executed directly. It defines functions only;
# it must not mutate global shell state beyond defining functions and read-only constants.

# ---------------------------------------------------------------------------
# Logging — everything goes to stderr so stdout stays machine-parseable.
# ---------------------------------------------------------------------------

myc_log() {
	printf 'myceliumctl: %s\n' "$*" >&2
}

myc_warn() {
	printf 'myceliumctl: warning: %s\n' "$*" >&2
}

# myc_die MESSAGE [EXIT_CODE]
# Print an error and exit. Default exit code is 1.
myc_die() {
	local code
	code="${2:-1}"
	printf 'myceliumctl: error: %s\n' "$1" >&2
	exit "$code"
}

# ---------------------------------------------------------------------------
# Dependency checks. We require only audited, off-the-shelf tools. We never
# hand-roll cryptography: REALITY keypairs and UUIDs come from xray, shortIds
# come from openssl. See docs/adr/0002-no-custom-cryptography.md.
# ---------------------------------------------------------------------------

# myc_have CMD -> 0 if CMD is on PATH, 1 otherwise.
myc_have() {
	command -v "$1" >/dev/null 2>&1
}

# myc_require CMD [HINT]
# Abort with a clear message if CMD is not on PATH.
myc_require() {
	local cmd hint
	cmd="$1"
	hint="${2:-}"
	if ! myc_have "$cmd"; then
		if [ -n "$hint" ]; then
			myc_die "required command not found in PATH: '$cmd' ($hint)"
		fi
		myc_die "required command not found in PATH: '$cmd'"
	fi
}

# myc_require_jq — jq is the rendering engine for Phase 0; it is mandatory.
myc_require_jq() {
	myc_require jq "install jq; it is the JSON rendering engine for Phase 0 tooling"
}

# myc_require_xray — REALITY keys and UUIDs MUST come from xray. We never
# generate them ourselves: no custom cryptography (ADR-0002).
myc_require_xray() {
	myc_require xray "install xray-core (>= v26.2.4) and put 'xray' on PATH; \
REALITY keypairs and UUIDs are generated by xray, never by hand"
}

# myc_require_openssl — shortIds are random hex from openssl rand.
myc_require_openssl() {
	myc_require openssl "install openssl; shortIds are generated with 'openssl rand -hex'"
}

# ---------------------------------------------------------------------------
# Crypto-material generators. THESE ARE WRAPPERS ONLY. Not one byte of key
# material is produced by this codebase — it all comes from audited tools.
# ---------------------------------------------------------------------------

# myc_xray_uuid — emit a single UUID from `xray uuid`.
myc_xray_uuid() {
	myc_require_xray
	local out
	out="$(xray uuid 2>/dev/null | tr -d '[:space:]')"
	if [ -z "$out" ]; then
		myc_die "'xray uuid' produced no output"
	fi
	printf '%s\n' "$out"
}

# myc_shortid [BYTES] — emit a REALITY shortId as lowercase hex.
# Default 8 bytes -> 16 hex chars (a common REALITY shortId length).
myc_shortid() {
	myc_require_openssl
	local bytes out
	bytes="${1:-8}"
	out="$(openssl rand -hex "$bytes" 2>/dev/null | tr -d '[:space:]')"
	if [ -z "$out" ]; then
		myc_die "'openssl rand -hex $bytes' produced no output"
	fi
	printf '%s\n' "$out"
}

# ---------------------------------------------------------------------------
# Timestamps. RFC 3339 / ISO 8601 UTC, second precision, portable across the
# BSD date on macOS and GNU date on Linux.
# ---------------------------------------------------------------------------

myc_now_utc() {
	date -u +%Y-%m-%dT%H:%M:%SZ
}

# ---------------------------------------------------------------------------
# Filesystem helpers.
# ---------------------------------------------------------------------------

# myc_mkdir_p DIR — create DIR (and parents) or die.
myc_mkdir_p() {
	mkdir -p -- "$1" || myc_die "could not create directory: $1"
}

# myc_dirname_of FILE — directory holding FILE.
myc_dirname_of() {
	dirname -- "$1"
}

# myc_atomic_write FILE < CONTENT
# Read stdin into FILE atomically (write to temp in the same dir, then mv).
myc_atomic_write() {
	local dest dir tmp
	dest="$1"
	dir="$(myc_dirname_of "$dest")"
	myc_mkdir_p "$dir"
	tmp="$(mktemp "${dir}/.myc.XXXXXX")" || myc_die "could not create temp file in $dir"
	cat >"$tmp" || { rm -f "$tmp"; myc_die "could not write temp file for $dest"; }
	mv -f "$tmp" "$dest" || { rm -f "$tmp"; myc_die "could not move temp file into place: $dest"; }
}

# ---------------------------------------------------------------------------
# Emitted params-knob validation (ADR-0038). The POLICY lives in internal/spec; these helpers only
# COMPARE against the numbers that package emits into control/vocab.json (.params_validation).
#
# WHY IT IS HERE. Two independent shell entrypoints judge a hysteria2 hop range — the client renderer
# (via myceliumctl, which sources lib/vocab.sh) and the firewall reconcile (via node-bootstrap, which
# does not) — and common.sh is the only file BOTH source. One comparator, therefore, and no second
# expression of the rule anywhere in the tree.
#
# WHY IT MATTERS. The range is a promise the CLIENT CONFIG makes and the FIREWALL keeps. When the two
# halves judged it separately they diverged, and the resulting state is invisible from the node:
# clients hop across ports nothing serves while verify_post_apply reports healthy, because it checks
# the service, the bind and a LOOPBACK handshake, and loopback never traverses PREROUTING.
# ---------------------------------------------------------------------------

# _myc_vocab_path — the Go-emitted vocabulary artifact, resolved the same way in both entrypoints.
_myc_vocab_path() {
	if [ -n "${MYC_VOCAB:-}" ]; then printf '%s' "$MYC_VOCAB"; return 0; fi
	printf '%s/control/vocab.json' "${ARTIFACT_ROOT:-${REPO_ROOT:-.}}"
}

# myc_hop_range_ok VALUE — succeed iff VALUE is a usable hysteria2 hop range under the EMITTED bounds.
# The empty string is NOT a range (it means "no hopping"); callers check that separately.
#
# FAIL-CLOSED on a vocab that carries no bounds: an older artifact beside a newer shell must yield NO
# range, which is the unconfigured state (no server_ports emitted, no REDIRECT installed) — never a
# permissive default. A permissive default here would hand clients a range with nothing behind it,
# which is the exact failure this contract exists to remove.
myc_hop_range_ok() {
	[ -n "${1:-}" ] || return 1
	# Reject more than one separator BEFORE splitting. `${v%%:*}` / `${v##*:}` take the OUTER fields, so
	# "2000:3000:4000" yields 2000 and 4000 — in bounds, ordered — and would be accepted, then handed to
	# iptables verbatim as `--dport 2000:3000:4000`, which it refuses. A value that passes validation and
	# cannot become a rule is the disagreement, not an edge case.
	case "$1" in *:*:*) return 1 ;; *:*) ;; *) return 1 ;; esac
	local lo="${1%%:*}" hi="${1##*:}"
	[ -n "$lo" ] && [ -n "$hi" ] || return 1
	case "$lo$hi" in *[!0-9]*) return 1 ;; esac
	local vocab min max cap
	vocab="$(_myc_vocab_path)"
	[ -f "$vocab" ] || return 1
	min="$(jq -r '.params_validation.hysteria2_hop_ports.min // empty' "$vocab" 2>/dev/null)"
	max="$(jq -r '.params_validation.hysteria2_hop_ports.max // empty' "$vocab" 2>/dev/null)"
	cap="$(jq -r '.params_validation.max_port_field_digits // empty' "$vocab" 2>/dev/null)"
	case "${min:-x}${max:-x}${cap:-x}" in *[!0-9]*) return 1 ;; esac
	# THE EMITTED DIGIT CAP, not a local rule (Audit-0010 F-006). Ownership had been collapsed for the
	# NUMBERS and left restated for the SHAPE, so `001024:065535` was accepted here and refused by the
	# owner: `test -ge` parses base 10, so a zero-padded field clears every numeric check. Two answers to
	# one input is the divergence ADR-0038 exists to remove.
	[ "${#lo}" -le "$cap" ] && [ "${#hi}" -le "$cap" ] || return 1
	[ "$lo" -ge "$min" ] && [ "$hi" -le "$max" ] && [ "$lo" -lt "$hi" ] || return 1

	# COLLISION, the renderer's half (Audit-0010 F-001). A REDIRECT covers every WAN-inbound UDP packet in
	# its range, so a range CONTAINING another served UDP port sends that family to the hysteria2 listener
	# — and nothing on the node reports it: the reach anchors are 127.0.0.1 and loopback never traverses a
	# `-i <wan>` PREROUTING rule. The firewall reconcile already refuses such a range; refusing it here too
	# is what stops a client being handed a range the node has decided not to make real.
	#
	# WHICH keys count as served UDP ports is POLICY and is emitted (.params_validation.udp_port_keys,
	# derived from the registry's UDP classes plus the AmneziaWG dataplane). Whether a number lies between
	# two others is not policy, so comparing here duplicates nothing.
	local params="${MYC_HOP_PARAMS:-${PARAMS_JSON:-}}"
	[ -n "$params" ] && [ -f "$params" ] || return 0
	local served k p
	served="$(jq -r '.hysteria2_port // empty' "$params" 2>/dev/null)"
	for k in $(jq -r '.params_validation.udp_port_keys[]? // empty' "$vocab" 2>/dev/null); do
		p="$(jq -r --arg k "$k" '.[$k] // empty' "$params" 2>/dev/null)"
		case "$p" in ''|*[!0-9]*) continue ;; esac
		[ "$p" = "$served" ] && continue
		if [ "$p" -ge "$lo" ] && [ "$p" -le "$hi" ]; then return 1; fi
	done
	return 0
}

# myc_hop_interval_ok VALUE — succeed iff VALUE matches the EMITTED hop-interval pattern.
#
# A duration cannot be bounded by two integers, so the owner emits the SHAPE (an ERE) instead. Until this
# existed the interval was operator-settable and judged by nobody (Audit-0010 F-005): a mistyped value
# reached the client config and the server render, and sing-box then refused the whole document — a
# converge that fails on every tick with a message about JSON rather than about the knob.
# Fail-closed on an artifact carrying no pattern, for the same reason the bounds do.
myc_hop_interval_ok() {
	[ -n "${1:-}" ] || return 1
	local vocab pat
	vocab="$(_myc_vocab_path)"
	[ -f "$vocab" ] || return 1
	pat="$(jq -r '.params_validation.hysteria2_hop_interval_pattern // empty' "$vocab" 2>/dev/null)"
	[ -n "$pat" ] || return 1
	# here-string, not a pipe: this is the function's RETURN VALUE under the entrypoint's
	# `set -euo pipefail`, and `grep -q` closing the pipe on a match would make a MATCH read as failure.
	grep -qE "$pat" <<<"$1"
}

# myc_hop_interval_default — the emitted default hop period. Empty when the vocab carries none, which
# the caller must treat as "do not emit an interval" rather than substituting a guess.
myc_hop_interval_default() {
	local vocab; vocab="$(_myc_vocab_path)"
	[ -f "$vocab" ] || { printf ''; return 0; }
	jq -r '.params_validation.hysteria2_hop_interval_default // empty' "$vocab" 2>/dev/null || printf ''
}
