// Copyright © 2026 mindicator & silicon bags quartet.
// SPDX-License-Identifier: AGPL-3.0-or-later
// This file is part of Mycelium, licensed under the GNU Affero General Public License v3.0 or
// later. See the LICENSE file in the repository root.

package spec

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
)

// FrontProxyFromParams resolves the node's direct address + the frontable transport's listen port from
// params (the same registry-default resolution the renderers use) and compiles the edge proxy config.
// node_address is required (fail-closed). The front's transport must be a registered frontable proto.
func FrontProxyFromParams(fc FrontConfig, params map[string]json.RawMessage) (string, error) {
	if err := fc.Validate(); err != nil {
		return "", err
	}
	if !fc.Enabled {
		return "", fmt.Errorf("front: cannot render an edge proxy for a disabled front")
	}
	nodeAddr, err := paramRequired(params, "node_address")
	if err != nil {
		return "", fmt.Errorf("front: %w", err)
	}
	var portKey, defPort string
	for i := range transportRegistry {
		if transportRegistry[i].Proto == fc.Transport {
			portKey = transportRegistry[i].PortKey
			defPort = strconv.Itoa(transportRegistry[i].DefaultPort)
			break
		}
	}
	if portKey == "" {
		return "", fmt.Errorf("front: transport %q has no registered listen port", fc.Transport)
	}
	return RenderFrontProxy(fc, nodeAddr, paramStr(params, portKey, defPort))
}

// RenderFrontProxy compiles a FrontConfig into the nginx config the OPERATOR deploys on their own edge
// host — the bring-your-own-domain front (ADR-0033 P2). It is pure text generation: nothing on a Mycelium
// node runs this; the operator points DNS for the front domain at their edge and installs this config.
//
//   - RELAY (default, doctrine-clean): an nginx `stream` server with ssl_preread does SNI-routed
//     TLS-PASSTHROUGH — it forwards the encrypted tunnel to the node WITHOUT terminating TLS, so the edge
//     learns only that a client reached an edge (no inner destination, no content) and holds NO TLS key;
//     the node's own certificate is served end to end. A non-matching SNI maps to an empty upstream and is
//     refused (fail-closed: only the front domain routes).
//   - TERMINATE (opt-in, ack-required): an nginx `http` TLS-terminating reverse proxy. The edge SEES the
//     user's source address + destination hostnames (a metadata trade-off — ADR-0026 / THREAT-MODEL);
//     emitted ONLY because the FrontConfig carries the explicit acknowledgement (Validate enforces it).
//
// nodeAddr/nodePort are the node's DIRECT address + the frontable transport's listen port (where the edge
// forwards). Both are config-injection-validated (host charset only) so an operator-supplied domain/host
// can never smuggle nginx directives. Pure + deterministic.
func RenderFrontProxy(fc FrontConfig, nodeAddr, nodePort string) (string, error) {
	if err := fc.Validate(); err != nil {
		return "", err
	}
	if !fc.Enabled {
		return "", fmt.Errorf("front: cannot render an edge proxy for a disabled front")
	}
	if !isSafeHost(fc.Domain) {
		return "", fmt.Errorf("front: domain %q is not a bare hostname (config-injection guard)", fc.Domain)
	}
	if !isSafeHost(nodeAddr) {
		return "", fmt.Errorf("front: node address %q is not a bare host/IP (config-injection guard)", nodeAddr)
	}
	p, err := strconv.Atoi(nodePort)
	if err != nil || p < 1 || p > 65535 {
		return "", fmt.Errorf("front: node port %q is not a positive integer in 1..65535", nodePort)
	}

	header := func(mode, extra string) string {
		return strings.Join([]string{
			"# Copyright © 2026 mindicator & silicon bags quartet.",
			"# SPDX-License-Identifier: AGPL-3.0-or-later",
			"# This file is part of Mycelium, licensed under the GNU Affero General Public License v3.0 or",
			"# later. See the LICENSE file in the repository root.",
			"#",
			"# Mycelium operator CDN/ingress front — " + mode + " mode (ADR-0033). Generated by myceliumctl.",
			"# Deploy on YOUR OWN edge host and point DNS for " + fc.Domain + " at it (core registers no domain).",
			extra,
			"# EFFICACY: a front is COMPLEMENTARY / last-resort — it adds reachability on IP/SNI-blocking",
			"# networks, but is NOT a fix for the destination-class throughput throttle (the in-region two-hop",
			"# is primary — THREAT-MODEL / ADR-0027). Prefer the two-hop for the hard target.",
			"",
		}, "\n")
	}

	upstream := nodeAddr + ":" + strconv.Itoa(p)
	if fc.EffectiveMode() == FrontModeRelay {
		var b strings.Builder
		b.WriteString(header("RELAY (TLS-passthrough, SNI-routed)",
			"# RELAY: forwards the encrypted tunnel to the node WITHOUT terminating TLS — the edge learns only\n"+
				"# that a client reached an edge, never the inner destination/content, and holds NO TLS key (the\n"+
				"# node's own certificate is served end to end). Requires the stock ngx_stream_ssl_preread module."))
		fmt.Fprintf(&b, "stream {\n")
		fmt.Fprintf(&b, "    map $ssl_preread_server_name $mycelium_front_upstream {\n")
		fmt.Fprintf(&b, "        default     \"\";\n")
		fmt.Fprintf(&b, "        %q    %q;\n", fc.Domain, upstream)
		fmt.Fprintf(&b, "    }\n")
		fmt.Fprintf(&b, "    server {\n")
		fmt.Fprintf(&b, "        listen 443;\n")
		fmt.Fprintf(&b, "        listen [::]:443;\n")
		fmt.Fprintf(&b, "        ssl_preread on;\n")
		fmt.Fprintf(&b, "        proxy_pass $mycelium_front_upstream;\n")
		fmt.Fprintf(&b, "    }\n")
		fmt.Fprintf(&b, "}\n")
		return b.String(), nil
	}

	// TERMINATE (ack-gated by Validate): TLS-terminating reverse proxy with WebSocket upgrade support.
	var b strings.Builder
	b.WriteString(header("TERMINATE (TLS-terminating reverse proxy)",
		"# WARNING — TERMINATE: this edge TERMINATES TLS, so it SEES the user's source address and the\n"+
			"# destination hostnames and hands both to wherever it runs (a metadata trade-off — ADR-0026 /\n"+
			"# THREAT-MODEL \"worse than neutral\"). You acknowledged this (ack_terminate_tradeoff=true); relay is\n"+
			"# the doctrine-clean default. Provide YOUR OWN real certificate for "+fc.Domain+" at the paths below."))
	fmt.Fprintf(&b, "http {\n")
	fmt.Fprintf(&b, "    map $http_upgrade $mycelium_connection_upgrade { default upgrade; \"\" close; }\n")
	fmt.Fprintf(&b, "    server {\n")
	fmt.Fprintf(&b, "        listen 443 ssl;\n")
	fmt.Fprintf(&b, "        listen [::]:443 ssl;\n")
	fmt.Fprintf(&b, "        http2 on;\n")
	fmt.Fprintf(&b, "        server_name %s;\n", fc.Domain)
	fmt.Fprintf(&b, "        ssl_certificate     /etc/ssl/mycelium-front/fullchain.pem;\n")
	fmt.Fprintf(&b, "        ssl_certificate_key /etc/ssl/mycelium-front/privkey.pem;\n")
	fmt.Fprintf(&b, "        location / {\n")
	fmt.Fprintf(&b, "            proxy_pass https://%s;\n", upstream)
	fmt.Fprintf(&b, "            proxy_ssl_server_name on;\n")
	fmt.Fprintf(&b, "            proxy_set_header Host $host;\n")
	fmt.Fprintf(&b, "            proxy_http_version 1.1;\n")
	fmt.Fprintf(&b, "            proxy_set_header Upgrade $http_upgrade;\n")
	fmt.Fprintf(&b, "            proxy_set_header Connection $mycelium_connection_upgrade;\n")
	fmt.Fprintf(&b, "        }\n")
	fmt.Fprintf(&b, "    }\n")
	fmt.Fprintf(&b, "}\n")
	return b.String(), nil
}

// isSafeHost reports whether s is a bare hostname or IP literal (optionally IPv6-bracketed) — the only
// shapes allowed into a generated nginx config. It rejects whitespace, quotes, braces, semicolons and any
// other character that could close a directive and inject configuration. Empty is unsafe.
func isSafeHost(s string) bool {
	if s == "" {
		return false
	}
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c >= 'A' && c <= 'Z', c >= 'a' && c <= 'z', c >= '0' && c <= '9':
		case c == '.' || c == '-' || c == ':' || c == '[' || c == ']':
		default:
			return false
		}
	}
	return true
}
